import { link } from "@/lib/guide/links";
import type { GuideEntry } from "@/lib/guide/types";

/**
 * Loop's built-in answers. Each states only what the platform actually
 * does today, in plain words, and links only to pages in the directory
 * (src/lib/guide/links.ts), which a test enforces. SUPER_ADMIN adds to
 * these from the Command Center; anything Loop cannot answer is collected
 * there so it can be answered once for everyone.
 *
 * Deliberately absent: prices, dates, numbers, promises about outcomes.
 * Those live on the pages themselves and change.
 */
const d = (id: string, question: string, answer: string, links: ReturnType<typeof link>[], keywords: string[] = []): GuideEntry => ({
  id: `default:${id}`, question, answer, links, keywords, source: "default",
});

export const DEFAULT_ENTRIES: GuideEntry[] = [
  d("what-is", "What is this platform?",
    "AAICBI is an ecosystem where people learn, training organizations run programs, employers find talent, and opportunities connect them. Trainees earn certificates that anyone can verify.",
    [link("/#ecosystem"), link("/courses")], ["about", "aaicbi", "purpose", "overview", "introduction", "mission", "site", "website"]),
  d("how-it-works", "How does this platform work?",
    "Three steps. Learn: trainees join programs from training organizations and earn verified certificates. Build and share: they work on projects and, if they choose, present what they learned. Get discovered: employers and organizations find people by skills and reach out.",
    [link("/#ecosystem"), link("/#join")], ["works", "explain", "tour", "steps", "process"]),
  d("who-are-you", "Who are you?",
    "I'm Loop, your guide to the ecosystem. I answer from written answers and take you to the right page. I'm not a person, and I can only help with finding your way around.",
    [link("/#ecosystem")], ["loop", "bot", "assistant", "chatbot", "name"]),
  d("create-account", "How do I create an account?",
    "Choose how you will use the platform and register: as a trainee, a training organization, an employer or an investor. Creating an account is free. Trainees confirm their email address first.",
    [link("/trainee/register"), link("/org/register"), link("/employer/register"), link("/investor/register")], ["signup", "register", "join", "account", "start", "begin"]),
  d("trainee-register", "How do I register as a trainee?",
    "Create a trainee account, confirm your email address, then browse programs and enrol in the ones you want. You only need an account when you want to act; you can look around without one.",
    [link("/trainee/register"), link("/courses")], ["student", "learner", "enrol", "enroll", "sign up"]),
  d("become-org", "How do I become a training organization?",
    "Register your organization. New organizations are reviewed before they go live. Once approved you can run your own programs and assessments, issue certificates with your own logo, and publish a public page, events and trainee videos.",
    [link("/org/register"), link("/org/login")], ["training organization", "academy", "institute", "school", "run training", "list my program", "list program", "provider"]),
  d("org-features", "What can a training organization do here?",
    "Run programs with structured modules and assessments, issue verified certificates carrying your own logo, publish a public organization page, announce events, share videos presented by your trainees, and see how your content is doing.",
    [link("/org/register"), link("/organizations")], ["features", "benefits", "offer", "tools", "dashboard"]),
  d("employer-take-part", "How can employers take part?",
    "Register as an employer. New employers are approved before they can use the platform. Then you can post roles, browse trainees who chose to be discoverable, and ask for an introduction. A trainee's contact details are only shared when they agree.",
    [link("/employer/register"), link("/jobs"), link("/trainees")], ["employer", "company", "recruit", "hire", "hiring", "talent", "business"]),
  d("post-job", "How do I post a job or opportunity?",
    "Register or sign in as an employer, then add a posting with its description, skills and closing date. Each posting is reviewed before it appears publicly.",
    [link("/employer/register"), link("/employer/login")], ["post", "vacancy", "advertise", "list", "opening", "recruit"]),
  d("apply-job", "How do I apply for a job?",
    "Open the role and choose Apply. You need a trainee account to apply, and when you do you choose exactly what to share with the employer. You can read every posting without an account.",
    [link("/jobs"), link("/trainee/register"), link("/trainee/login")], ["apply", "application", "cv", "resume", "submit"]),
  d("find-training", "How do I find a training program?",
    "Browse the public program catalogue, or search by a skill to see programs, organizations, videos and events that match. Each program page shows its details and price.",
    [link("/courses"), link("/search"), link("/organizations")], ["course", "class", "learn", "study", "bootcamp", "program", "find", "skill", "upskill"]),
  d("find-jobs", "Where can I find jobs and opportunities?",
    "Open roles from approved employers are listed on the opportunities page, and you can search by role, skill or company. Applying needs a trainee account.",
    [link("/jobs"), link("/trainee/register")], ["jobs", "vacancies", "openings", "internship", "work", "career", "hiring", "opportunities"]),
  d("find-orgs", "How can I find training organizations?",
    "The organizations page lists every organization with a public page. You can see what each teaches, its events and its videos, and follow the ones you like once you have an account.",
    [link("/organizations"), link("/search")], ["organizations", "academy", "institute", "school", "provider", "who trains"]),
  d("find-trainees", "Where can I see trainees and their skills?",
    "The trainees page lists people who chose to make their profile public, with their skills and place. Profiles are private unless the trainee turns that on, and contact details are never shown publicly.",
    [link("/trainees"), link("/employer/register")], ["talent", "candidates", "people", "students", "learners", "graduates", "profiles"]),
  d("events", "Where can I see upcoming events?",
    "Organizations announce open days, workshops and demo days on the events page. Registration happens on the organization's own link.",
    [link("/events"), link("/organizations")], ["workshop", "webinar", "open day", "meetup", "seminar", "calendar", "happening"]),
  d("videos", "Where can I watch educational videos?",
    "Trainees present short educational videos that their organization publishes. You can watch them without an account; liking, saving and commenting need a trainee account.",
    [link("/learn"), link("/feed")], ["watch", "youtube", "lessons", "tutorial", "clip"]),
  d("verify-certificate", "How do I verify a certificate?",
    "Every certificate has a unique code and a public page. Enter the code on the verification page to check it is genuine. No account is needed.",
    [link("/certificate")], ["verify", "check", "genuine", "authentic", "credential", "code", "valid", "fake"]),
  d("get-certificate", "How do I get a certificate?",
    "Finish a program and its assessments and the certificate is issued to you, with a unique code anyone can use to check it.",
    [link("/courses"), link("/certificate")], ["certificate", "certification", "diploma", "earn", "credential", "complete", "finish"]),
  d("investor", "How can investors take part?",
    "Register as an investor. New investors are approved first. Then you can discover training organizations by the skills they teach, follow organizations privately, and see pitches that trainees choose to share.",
    [link("/investor/register"), link("/organizations")], ["invest", "investment", "funding", "fund", "pitch", "venture", "back"]),
  d("login", "How do I sign in?",
    "Use the sign-in page for your kind of account: trainee, organization, employer, investor or staff.",
    [link("/trainee/login"), link("/org/login"), link("/employer/login"), link("/investor/login"), link("/admin/login")], ["login", "log in", "sign in", "access", "enter"]),
  d("reset-password", "I forgot my password",
    "Trainees and staff can reset a password by email. For an organization, employer or investor account, open its sign-in page and follow the link there.",
    [link("/trainee/forgot-password"), link("/admin/forgot-password")], ["password", "reset", "forgot", "locked out", "cannot log in", "can't login"]),
  d("cost", "Is it free to join?",
    "Creating an account is free. Each program shows its price, or that it is free, on its own page, and some programs let you try the first modules before paying.",
    [link("/courses"), link("/trainee/register")], ["free", "price", "cost", "fee", "pay", "payment", "cheap", "afford", "naira"]),
  d("privacy", "Who can see my profile?",
    "Only what you choose. A trainee profile is private until you set it to public in your settings, and contact details are never shown publicly. Employers see more only if you turn on discoverability, and you decide what to share when you apply or accept an introduction.",
    [link("/trainee/settings"), link("/trainees")], ["privacy", "private", "public", "visible", "data", "safe", "secure", "personal"]),
  d("contact", "How do I contact an organization, employer or trainee?",
    "Today: employers can ask a trainee for an introduction, trainees can apply to roles, trainees can message their cohort and instructors inside their courses, and every organization has a public page. You need an account for any of these.",
    [link("/organizations"), link("/jobs"), link("/trainee/register")], ["message", "chat", "dm", "contact", "reach", "email", "talk", "speak", "introduce"]),
  d("follow-org", "How do I follow an organization?",
    "Sign in as a trainee, open the organization's page and choose Follow. Posts from organizations you follow get a boost in your feed.",
    [link("/organizations"), link("/trainee/login")], ["follow", "subscribe", "save", "favourite", "favorite"]),
  d("phone", "Does it work on my phone?",
    "Yes. The whole platform is built to work on a phone, and the cards on the home page swipe sideways.",
    [link("/#ecosystem")], ["mobile", "android", "iphone", "tablet", "app", "device", "small screen"]),
  d("buddy", "Can I get AI help with my studies?",
    "Signed-in trainees can use their Learning Buddy for study support, when it is turned on in their settings. I'm Loop, the guide: I help you find your way around, and I don't answer course or assessment questions.",
    [link("/trainee/buddy"), link("/trainee/settings")], ["ai", "buddy", "study", "tutor", "assistant", "learning buddy"]),
  d("exam-answers", "Can you help me with exam answers?",
    "No. I help you find your way around the platform and I don't answer course, exam or assignment questions. Your lessons and your Learning Buddy are the place for study help.",
    [link("/trainee/buddy")], ["exam", "test", "quiz", "assessment", "assignment", "answers", "cheat"]),
  d("featured", "How does an organization get featured?",
    "Featured organizations are chosen by published criteria that reward steady, useful content from organizations that teach, such as complete programs, regular videos by different trainees and verified certificates. Volume alone does not help.",
    [link("/organizations"), link("/org/register")], ["featured", "trending", "popular", "ranking", "visibility", "promote", "advertise", "boost"]),
];
